# Generated by Django 4.2 on 2024-05-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=5, unique=True, verbose_name='Символьный знак')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сбора данных')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Значение')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cur', to='show_rates.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency', 'date'), name='unique_currency_date'),
        ),
    ]
